### ISSUE TITLE
400g3 ql3x

### ISSUE THREAD

**Issue by HSHking** [swy1996/OpenCore_for_HP400G3DM-ql3x#1]
hp 400g3 ql3x?

**Comment by swy1996** [comment]
yes it's pc model is hp400g3 and cpu is ql3x（intel core i7 7820hk es）image show i3 it's show error never mind and it's      
BIOS must be modified and flash

**Comment by HSHking** [comment]
Thanks for your efi and reply,we are

**Comment by HSHking** [comment]
thanks a lot,we are the same model

**Comment by HSHking** [comment]
your efi really helped me a lot

**Comment by swy1996** [comment]
if you use standard cpu like i5-7500t, you can search boot-args in config.plist and delete -disablegfxfirmware.This will make your computer sleep better.and you may need to change the ID of the video card in config.plist-DeviceProperties-AAPL,ig-platform-id and device-id(if i5-7500t hd630 you can google search this id).Finally, you may have to modify the system's three codes(SystemSerialNumber,SystemUUID,MLB). Good luck！

**Comment by HSHking** [comment]
Thank you from the bottom of my heart,By using your efi, I installed the Hackintosh in my hp 400g3(qlx) successfully and rapidly，your efi is very perfect!!!
