### ISSUE TITLE
哈喽请问有遇到有线网卡不能驱动的问题吗？

### ISSUE THREAD

**Issue by iiKanow** [swy1996/OpenCore_for_HP400G3DM-ql3x#3]
装了两台400g3+ql3x，mojave系统。有线网络都没有驱动。
是系统版本的问题吗？
还有就是就是同求RTC补丁啊。工作用机也不敢乱折腾

**Comment by iiKanow** [comment]
升级了catalina有线可以驱动了，不同系统oc原来不通用啊
感谢

**Comment by swy1996** [comment]
应该通用的啊 不过现在都用10.15以上的系统了 最近适配下bigsur 一直鸽了好久
